//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AvCompo.Tools {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AvCompo.Tools.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی.
        /// </summary>
        public static string App_StringKeys_Accesslevel_checkbox {
            get {
                return ResourceManager.GetString("App_StringKeys_Accesslevel_checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت دسترسی کاربر.
        /// </summary>
        public static string App_StringKeys_Accesslevel_Title {
            get {
                return ResourceManager.GetString("App_StringKeys_Accesslevel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک دسترسی.
        /// </summary>
        public static string App_StringKeys_Accesslevel_Url {
            get {
                return ResourceManager.GetString("App_StringKeys_Accesslevel_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان بخش.
        /// </summary>
        public static string App_StringKeys_Accesslevel_Username {
            get {
                return ResourceManager.GetString("App_StringKeys_Accesslevel_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی.
        /// </summary>
        public static string APP_StringKeys_Account_Fullname {
            get {
                return ResourceManager.GetString("APP_StringKeys_Account_Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور.
        /// </summary>
        public static string APP_StringKeys_Account_Password {
            get {
                return ResourceManager.GetString("APP_StringKeys_Account_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string APP_StringKeys_Account_Username {
            get {
                return ResourceManager.GetString("APP_StringKeys_Account_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string APP_StringKeys_AccountList_Active {
            get {
                return ResourceManager.GetString("APP_StringKeys_AccountList_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت کاربر.
        /// </summary>
        public static string APP_StringKeys_AccountList_Pgae_Title {
            get {
                return ResourceManager.GetString("APP_StringKeys_AccountList_Pgae_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت اموال.
        /// </summary>
        public static string APP_StringKeys_Add_Asset_Management {
            get {
                return ResourceManager.GetString("APP_StringKeys_Add_Asset_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن نوع اموال.
        /// </summary>
        public static string APP_StringKeys_Add_Asset_Type {
            get {
                return ResourceManager.GetString("APP_StringKeys_Add_Asset_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرسنل جدید.
        /// </summary>
        public static string APP_StringKeys_Add_New_Personnel {
            get {
                return ResourceManager.GetString("APP_StringKeys_Add_New_Personnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت لیست اموال.
        /// </summary>
        public static string APP_StringKeys_Add_Product_List {
            get {
                return ResourceManager.GetString("APP_StringKeys_Add_Product_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزودن زیرمجموعه.
        /// </summary>
        public static string APP_StringKeys_Add_Sub_Location {
            get {
                return ResourceManager.GetString("APP_StringKeys_Add_Sub_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافه کردن پرسنل زیرمجموعه.
        /// </summary>
        public static string APP_StringKeys_Add_Sub_Personnel {
            get {
                return ResourceManager.GetString("APP_StringKeys_Add_Sub_Personnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string APP_StringKeys_AddAccount_Edit {
            get {
                return ResourceManager.GetString("APP_StringKeys_AddAccount_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست کاربران سامانه.
        /// </summary>
        public static string APP_StringKeys_AddAccount_Page_Title {
            get {
                return ResourceManager.GetString("APP_StringKeys_AddAccount_Page_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر جدید.
        /// </summary>
        public static string APP_StringKeys_AddNewAccount {
            get {
                return ResourceManager.GetString("APP_StringKeys_AddNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد تأیید شده.
        /// </summary>
        public static string APP_StringKeys_Approved_Count {
            get {
                return ResourceManager.GetString("APP_StringKeys_Approved_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام اموال.
        /// </summary>
        public static string APP_StringKeys_Asset_Name {
            get {
                return ResourceManager.GetString("APP_StringKeys_Asset_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرپرست.
        /// </summary>
        public static string APP_StringKeys_Asset_ProductType_Parent {
            get {
                return ResourceManager.GetString("APP_StringKeys_Asset_ProductType_Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سریال اموال.
        /// </summary>
        public static string APP_StringKeys_Asset_Serial {
            get {
                return ResourceManager.GetString("APP_StringKeys_Asset_Serial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع اموال.
        /// </summary>
        public static string APP_StringKeys_Asset_Type {
            get {
                return ResourceManager.GetString("APP_StringKeys_Asset_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد نوع اموال.
        /// </summary>
        public static string APP_StringKeys_Asset_Type_Code {
            get {
                return ResourceManager.GetString("APP_StringKeys_Asset_Type_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو.
        /// </summary>
        public static string APP_StringKeys_Cancel {
            get {
                return ResourceManager.GetString("APP_StringKeys_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابتدا ثابت کنید روبات نیستید!.
        /// </summary>
        public static string App_StringKeys_Capcaptcha_Check {
            get {
                return ResourceManager.GetString("App_StringKeys_Capcaptcha_Check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از ویرایش موارد زیر مطمئن هستید؟.
        /// </summary>
        public static string APP_StringKeys_Check_Before_Edit {
            get {
                return ResourceManager.GetString("APP_StringKeys_Check_Before_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از حذف موارد زیر مطمئن هستید؟.
        /// </summary>
        public static string APP_StringKeys_Check_Before_Remove {
            get {
                return ResourceManager.GetString("APP_StringKeys_Check_Before_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ویرایش &quot;گره&quot; موردنظر از درختواره وجود ندارد.
        /// </summary>
        public static string APP_StringKeys_Check_Treeview_AllParent {
            get {
                return ResourceManager.GetString("APP_StringKeys_Check_Treeview_AllParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گره موردنظر قابل انتخاب/ویرایش نیست.
        /// </summary>
        public static string APP_StringKeys_Check_Treeview_NotChoosable {
            get {
                return ResourceManager.GetString("APP_StringKeys_Check_Treeview_NotChoosable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتخاب.
        /// </summary>
        public static string APP_StringKeys_Choose {
            get {
                return ResourceManager.GetString("APP_StringKeys_Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد.
        /// </summary>
        public static string APP_StringKeys_Code {
            get {
                return ResourceManager.GetString("APP_StringKeys_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تائید.
        /// </summary>
        public static string APP_StringKeys_Confirm {
            get {
                return ResourceManager.GetString("APP_StringKeys_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرکز هزینه.
        /// </summary>
        public static string APP_StringKeys_CostCenter {
            get {
                return ResourceManager.GetString("APP_StringKeys_CostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ و ساعت.
        /// </summary>
        public static string APP_StringKeys_DateTime {
            get {
                return ResourceManager.GetString("APP_StringKeys_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما به این صفحه دسترسی ندارید لطفا با مدیر سیستم تماس بگیرید.
        /// </summary>
        public static string APP_StringKeys_Deadend_Error_text {
            get {
                return ResourceManager.GetString("APP_StringKeys_Deadend_Error_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این صفحه موجود نیست.
        /// </summary>
        public static string APP_StringKeys_Deadend_Title {
            get {
                return ResourceManager.GetString("APP_StringKeys_Deadend_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیش فرض.
        /// </summary>
        public static string APP_StringKeys_Default {
            get {
                return ResourceManager.GetString("APP_StringKeys_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string APP_StringKeys_Delete {
            get {
                return ResourceManager.GetString("APP_StringKeys_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پرسنلی تکراری است.
        /// </summary>
        public static string APP_StringKeys_Duplicate_Personnel_Code {
            get {
                return ResourceManager.GetString("APP_StringKeys_Duplicate_Personnel_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری تکراری است.
        /// </summary>
        public static string APP_StringKeys_Duplicate_Username {
            get {
                return ResourceManager.GetString("APP_StringKeys_Duplicate_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string APP_StringKeys_Edit {
            get {
                return ResourceManager.GetString("APP_StringKeys_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش عنوان اموال.
        /// </summary>
        public static string APP_StringKeys_Edit_Asset_Title {
            get {
                return ResourceManager.GetString("APP_StringKeys_Edit_Asset_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش پرسنل.
        /// </summary>
        public static string APP_StringKeys_Edit_Personnel {
            get {
                return ResourceManager.GetString("APP_StringKeys_Edit_Personnel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توکن کاربری معتبر نیست.
        /// </summary>
        public static string APP_StringKeys_Error_TokenInvalid {
            get {
                return ResourceManager.GetString("APP_StringKeys_Error_TokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هم اکنون نمی توانید فایل دیگری را آپلود کنید. دقایقی دیگر تلاش کنید.
        /// </summary>
        public static string APP_StringKeys_Error_Too_Much_Attempt {
            get {
                return ResourceManager.GetString("APP_StringKeys_Error_Too_Much_Attempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انجام عملیات مشکلی بوجود آمده است.
        /// </summary>
        public static string APP_StringKeys_Error_Unexpected {
            get {
                return ResourceManager.GetString("APP_StringKeys_Error_Unexpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوکیشن اظهار شده.
        /// </summary>
        public static string APP_StringKeys_Expressed_Location {
            get {
                return ResourceManager.GetString("APP_StringKeys_Expressed_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد کالا.
        /// </summary>
        public static string APP_StringKeys_Field_Count {
            get {
                return ResourceManager.GetString("APP_StringKeys_Field_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string APP_StringKeys_Field_Description {
            get {
                return ResourceManager.GetString("APP_StringKeys_Field_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تگ EPC.
        /// </summary>
        public static string APP_StringKeys_Field_EPC_Tag {
            get {
                return ResourceManager.GetString("APP_StringKeys_Field_EPC_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مکان.
        /// </summary>
        public static string APP_StringKeys_Field_Location_Name {
            get {
                return ResourceManager.GetString("APP_StringKeys_Field_Location_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مکان استقرار اموال.
        /// </summary>
        public static string APP_StringKeys_Field_LocationCode {
            get {
                return ResourceManager.GetString("APP_StringKeys_Field_LocationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string APP_StringKeys_Field_Name {
            get {
                return ResourceManager.GetString("APP_StringKeys_Field_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پرسنل.
        /// </summary>
        public static string APP_StringKeys_Field_PersonelCode {
            get {
                return ResourceManager.GetString("APP_StringKeys_Field_PersonelCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست پرسنل.
        /// </summary>
        public static string APP_StringKeys_Field_PersonelList {
            get {
                return ResourceManager.GetString("APP_StringKeys_Field_PersonelList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام پرسنل.
        /// </summary>
        public static string APP_StringKeys_Field_PersonelName {
            get {
                return ResourceManager.GetString("APP_StringKeys_Field_PersonelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی.
        /// </summary>
        public static string APP_StringKeys_Field_PersonelNationalCode {
            get {
                return ResourceManager.GetString("APP_StringKeys_Field_PersonelNationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام اموال.
        /// </summary>
        public static string APP_StringKeys_Field_ProductName {
            get {
                return ResourceManager.GetString("APP_StringKeys_Field_ProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سریال اموال.
        /// </summary>
        public static string APP_StringKeys_Field_ProductSerial {
            get {
                return ResourceManager.GetString("APP_StringKeys_Field_ProductSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع اموال.
        /// </summary>
        public static string APP_StringKeys_Field_ProductTypeCode {
            get {
                return ResourceManager.GetString("APP_StringKeys_Field_ProductTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام نوع اموال.
        /// </summary>
        public static string APP_StringKeys_Field_ProductTypeTitle {
            get {
                return ResourceManager.GetString("APP_StringKeys_Field_ProductTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد اموال.
        /// </summary>
        public static string APP_StringKeys_Field_ProductUnit {
            get {
                return ResourceManager.GetString("APP_StringKeys_Field_ProductUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجوی پرسنل.
        /// </summary>
        public static string APP_StringKeys_Field_SearchPersonel {
            get {
                return ResourceManager.GetString("APP_StringKeys_Field_SearchPersonel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فایل.
        /// </summary>
        public static string APP_StringKeys_FileName {
            get {
                return ResourceManager.GetString("APP_StringKeys_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست سامانه مالی (اطلاعات قبلی).
        /// </summary>
        public static string APP_StringKeys_Financial_System_List_Prev_Info {
            get {
                return ResourceManager.GetString("APP_StringKeys_Financial_System_List_Prev_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت نمونه Excel.
        /// </summary>
        public static string APP_StringKeys_Get_Sample_Excel {
            get {
                return ResourceManager.GetString("APP_StringKeys_Get_Sample_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیرفعال.
        /// </summary>
        public static string APP_StringKeys_InActive {
            get {
                return ResourceManager.GetString("APP_StringKeys_InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع دریافت.
        /// </summary>
        public static string APP_StringKeys_InputType {
            get {
                return ResourceManager.GetString("APP_StringKeys_InputType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد عملیات اموال گردانی.
        /// </summary>
        public static string APP_StringKeys_Inventory_HeaderId {
            get {
                return ResourceManager.GetString("APP_StringKeys_Inventory_HeaderId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت اموال گردانی.
        /// </summary>
        public static string APP_StringKeys_InventoryStatus {
            get {
                return ResourceManager.GetString("APP_StringKeys_InventoryStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صحیح.
        /// </summary>
        public static string APP_StringKeys_InventoryStatus_Correct {
            get {
                return ResourceManager.GetString("APP_StringKeys_InventoryStatus_Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف شده.
        /// </summary>
        public static string APP_StringKeys_InventoryStatus_Deleted {
            get {
                return ResourceManager.GetString("APP_StringKeys_InventoryStatus_Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافی.
        /// </summary>
        public static string APP_StringKeys_InventoryStatus_Extra {
            get {
                return ResourceManager.GetString("APP_StringKeys_InventoryStatus_Extra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافی-افزودن دستی.
        /// </summary>
        public static string APP_StringKeys_InventoryStatus_ExtraEntered {
            get {
                return ResourceManager.GetString("APP_StringKeys_InventoryStatus_ExtraEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نادیده گرفته شده.
        /// </summary>
        public static string APP_StringKeys_InventoryStatus_Ignore {
            get {
                return ResourceManager.GetString("APP_StringKeys_InventoryStatus_Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        public static string APP_StringKeys_InventoryStatus_InCorrect {
            get {
                return ResourceManager.GetString("APP_StringKeys_InventoryStatus_InCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تگ خطا-خروج دستی.
        /// </summary>
        public static string APP_StringKeys_InventoryStatus_IncorrectExited {
            get {
                return ResourceManager.GetString("APP_StringKeys_InventoryStatus_IncorrectExited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسایی دستی.
        /// </summary>
        public static string APP_StringKeys_InventoryStatus_ManuallyAdded {
            get {
                return ResourceManager.GetString("APP_StringKeys_InventoryStatus_ManuallyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی شما موقتا غیرفعال شد.
        /// </summary>
        public static string APP_StringKeys_Ip_Banned {
            get {
                return ResourceManager.GetString("APP_StringKeys_Ip_Banned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال بارگذاری ....
        /// </summary>
        public static string APP_StringKeys_Loading {
            get {
                return ResourceManager.GetString("APP_StringKeys_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مکان.
        /// </summary>
        public static string APP_StringKeys_Location {
            get {
                return ResourceManager.GetString("APP_StringKeys_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد مکان.
        /// </summary>
        public static string APP_StringKeys_Location_Code {
            get {
                return ResourceManager.GetString("APP_StringKeys_Location_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت مکان‌ها.
        /// </summary>
        public static string App_StringKeys_Location_Management {
            get {
                return ResourceManager.GetString("App_StringKeys_Location_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مکان.
        /// </summary>
        public static string APP_StringKeys_Location_Name {
            get {
                return ResourceManager.GetString("APP_StringKeys_Location_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درختواره مکان.
        /// </summary>
        public static string APP_StringKeys_Location_Treeview {
            get {
                return ResourceManager.GetString("APP_StringKeys_Location_Treeview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string APP_StringKeys_Logout {
            get {
                return ResourceManager.GetString("APP_StringKeys_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت اموال.
        /// </summary>
        public static string APP_StringKeys_Manage_Assets {
            get {
                return ResourceManager.GetString("APP_StringKeys_Manage_Assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انجام عملیات مشکلی بوجود آمده است.
        /// </summary>
        public static string APP_StringKeys_Message_Failed {
            get {
                return ResourceManager.GetString("APP_StringKeys_Message_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف اطلاعات به علت وجود اطلاعات زیرمجموعه ممکن نیست.
        /// </summary>
        public static string APP_StringKeys_Message_Failed_Remove_HasChild {
            get {
                return ResourceManager.GetString("APP_StringKeys_Message_Failed_Remove_HasChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا رمز عبور اشتباه است.
        /// </summary>
        public static string APP_StringKeys_Message_LoginFailed {
            get {
                return ResourceManager.GetString("APP_StringKeys_Message_LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با موفقیت انجام شد.
        /// </summary>
        public static string APP_StringKeys_Message_Success {
            get {
                return ResourceManager.GetString("APP_StringKeys_Message_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان اموال جدید.
        /// </summary>
        public static string APP_StringKeys_New_Asset_Title {
            get {
                return ResourceManager.GetString("APP_StringKeys_New_Asset_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست جدید نهایی.
        /// </summary>
        public static string APP_StringKeys_New_Final_List {
            get {
                return ResourceManager.GetString("APP_StringKeys_New_Final_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هیچ موردی انتخاب نشده است.
        /// </summary>
        public static string APP_StringKeys_No_Items_Selected {
            get {
                return ResourceManager.GetString("APP_StringKeys_No_Items_Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخص نشده.
        /// </summary>
        public static string APP_StringKeys_NotChoosed {
            get {
                return ResourceManager.GetString("APP_StringKeys_NotChoosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرسنل یافت نشد.
        /// </summary>
        public static string APP_StringKeys_NotFound_Personel {
            get {
                return ResourceManager.GetString("APP_StringKeys_NotFound_Personel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد اموال اختصاص داده شده.
        /// </summary>
        public static string APP_StringKeys_Num_Of_Assets_Allocated {
            get {
                return ResourceManager.GetString("APP_StringKeys_Num_Of_Assets_Allocated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ها.
        /// </summary>
        public static string APP_StringKeys_Operations {
            get {
                return ResourceManager.GetString("APP_StringKeys_Operations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پرسنل سرپرست.
        /// </summary>
        public static string APP_StringKeys_Parent_Personnel_Code {
            get {
                return ResourceManager.GetString("APP_StringKeys_Parent_Personnel_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور.
        /// </summary>
        public static string APP_StringKeys_Password {
            get {
                return ResourceManager.GetString("APP_StringKeys_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور باید شامل حداقل یک عدد، یک حرف بزرگ و یک علامت خاص (!@#$&amp;*) باشد.
        /// </summary>
        public static string APP_StringKeys_Password_Validation_Chars {
            get {
                return ResourceManager.GetString("APP_StringKeys_Password_Validation_Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری و رمز عبور نمیتواند برابر باشد.
        /// </summary>
        public static string APP_StringKeys_Password_Validation_Equals_Username {
            get {
                return ResourceManager.GetString("APP_StringKeys_Password_Validation_Equals_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ و ساعت شمسی.
        /// </summary>
        public static string APP_StringKeys_PersianDateTime {
            get {
                return ResourceManager.GetString("APP_StringKeys_PersianDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اموال پرسنل.
        /// </summary>
        public static string APP_StringKeys_Personel_Assets {
            get {
                return ResourceManager.GetString("APP_StringKeys_Personel_Assets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست پرسنل.
        /// </summary>
        public static string APP_StringKeys_Personel_List {
            get {
                return ResourceManager.GetString("APP_StringKeys_Personel_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پرسنل.
        /// </summary>
        public static string APP_StringKeys_Personnel_Code {
            get {
                return ResourceManager.GetString("APP_StringKeys_Personnel_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیریت پرسنل.
        /// </summary>
        public static string App_StringKeys_Personnel_Management {
            get {
                return ResourceManager.GetString("App_StringKeys_Personnel_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  نشان کردن لینک.
        /// </summary>
        public static string APP_StringKeys_Pin_Link {
            get {
                return ResourceManager.GetString("APP_StringKeys_Pin_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این صفحه قبلا نشان شده است..
        /// </summary>
        public static string APP_StringKeys_Pin_Link_Error {
            get {
                return ResourceManager.GetString("APP_StringKeys_Pin_Link_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش کاربر.
        /// </summary>
        public static string APP_StringKeys_Role {
            get {
                return ResourceManager.GetString("APP_StringKeys_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره.
        /// </summary>
        public static string APP_StringKeys_Save {
            get {
                return ResourceManager.GetString("APP_StringKeys_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string APP_StringKeys_Search {
            get {
                return ResourceManager.GetString("APP_StringKeys_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست اموال در اختیار.
        /// </summary>
        public static string APP_StringKeys_SelfExpression_Asset_List {
            get {
                return ResourceManager.GetString("APP_StringKeys_SelfExpression_Asset_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string APP_StringKeys_Status {
            get {
                return ResourceManager.GetString("APP_StringKeys_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرپرست.
        /// </summary>
        public static string APP_StringKeys_Supervisor {
            get {
                return ResourceManager.GetString("APP_StringKeys_Supervisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه تگ.
        /// </summary>
        public static string APP_StringKeys_Tag_Epc {
            get {
                return ResourceManager.GetString("APP_StringKeys_Tag_Epc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سابقه اموال.
        /// </summary>
        public static string APP_StringKeys_Tag_History {
            get {
                return ResourceManager.GetString("APP_StringKeys_Tag_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اموال با سریال &quot;{0}&quot; قبلا رجیستر شده است.
        /// </summary>
        public static string APP_StringKeys_Tag_IsRegistered {
            get {
                return ResourceManager.GetString("APP_StringKeys_Tag_IsRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اموال رجیستر نشده است.
        /// </summary>
        public static string APP_StringKeys_Tag_NotRegistered {
            get {
                return ResourceManager.GetString("APP_StringKeys_Tag_NotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعریف اموال.
        /// </summary>
        public static string APP_StringKeys_Tag_Register {
            get {
                return ResourceManager.GetString("APP_StringKeys_Tag_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گزارش اموال ثبت شده.
        /// </summary>
        public static string APP_StringKeys_Tag_ReportRegister {
            get {
                return ResourceManager.GetString("APP_StringKeys_Tag_ReportRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف از نشان شده‌ها.
        /// </summary>
        public static string APP_StringKeys_UnPin_Link {
            get {
                return ResourceManager.GetString("APP_StringKeys_UnPin_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش نوع اموال.
        /// </summary>
        public static string APP_StringKeys_Update_Asset_Type {
            get {
                return ResourceManager.GetString("APP_StringKeys_Update_Asset_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری اکسل.
        /// </summary>
        public static string APP_StringKeys_Upload_Excel {
            get {
                return ResourceManager.GetString("APP_StringKeys_Upload_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری فایل Excel.
        /// </summary>
        public static string APP_StringKeys_Upload_Excel_File {
            get {
                return ResourceManager.GetString("APP_StringKeys_Upload_Excel_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارگذاری فایل.
        /// </summary>
        public static string APP_StringKeys_Upload_File {
            get {
                return ResourceManager.GetString("APP_StringKeys_Upload_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string APP_StringKeys_User {
            get {
                return ResourceManager.GetString("APP_StringKeys_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی شما موقتا غیرفعال شد.
        /// </summary>
        public static string APP_StringKeys_User_Locked {
            get {
                return ResourceManager.GetString("APP_StringKeys_User_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string APP_StringKeys_Username {
            get {
                return ResourceManager.GetString("APP_StringKeys_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل یک مورد را انتخاب کنید.
        /// </summary>
        public static string APP_StringKeys_Validation_Choose_One_AtLeast {
            get {
                return ResourceManager.GetString("APP_StringKeys_Validation_Choose_One_AtLeast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیست اطلاعات خالی است.
        /// </summary>
        public static string APP_StringKeys_Validation_DataEmpty {
            get {
                return ResourceManager.GetString("APP_StringKeys_Validation_DataEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلد {0} تکراری است.
        /// </summary>
        public static string APP_StringKeys_Validation_Duplicate {
            get {
                return ResourceManager.GetString("APP_StringKeys_Validation_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل وارد شده در فرمت مناسب نیست.
        /// </summary>
        public static string APP_StringKeys_Validation_File_Format {
            get {
                return ResourceManager.GetString("APP_StringKeys_Validation_File_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0} باید بیشتر از صفر باشد.
        /// </summary>
        public static string APP_StringKeys_Validation_GreaterThanZero {
            get {
                return ResourceManager.GetString("APP_StringKeys_Validation_GreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشخصات کاربری یافت نشد.
        /// </summary>
        public static string APP_StringKeys_Validation_LoginFail {
            get {
                return ResourceManager.GetString("APP_StringKeys_Validation_LoginFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداکثر سایز مجاز برای آپلود فایل {0} است.
        /// </summary>
        public static string APP_StringKeys_Validation_Max_Allow_Size {
            get {
                return ResourceManager.GetString("APP_StringKeys_Validation_Max_Allow_Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات فیلد {0} الزامی است.
        /// </summary>
        public static string APP_StringKeys_Validation_Required {
            get {
                return ResourceManager.GetString("APP_StringKeys_Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات فیلد کلمه عبور الزامی است.
        /// </summary>
        public static string APP_StringKeys_Validation_Required_Pass {
            get {
                return ResourceManager.GetString("APP_StringKeys_Validation_Required_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول فیلد {0} باید حداکثر {1} باشد.
        /// </summary>
        public static string APP_StringKeys_Validation_Stringlength_Max {
            get {
                return ResourceManager.GetString("APP_StringKeys_Validation_Stringlength_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول فیلد {0} باید حداقل {1} باشد.
        /// </summary>
        public static string APP_StringKeys_Validation_Stringlength_Min {
            get {
                return ResourceManager.GetString("APP_StringKeys_Validation_Stringlength_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود.
        /// </summary>
        public static string APP_StringKeys_View_Account_Login {
            get {
                return ResourceManager.GetString("APP_StringKeys_View_Account_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه نتایج.
        /// </summary>
        public static string APP_StringKeys_View_AllItemsText {
            get {
                return ResourceManager.GetString("APP_StringKeys_View_AllItemsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید اموال در اختیار پرسنل.
        /// </summary>
        public static string APP_StringKeys_View_Approve_Self_Expression {
            get {
                return ResourceManager.GetString("APP_StringKeys_View_Approve_Self_Expression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه اصلی.
        /// </summary>
        public static string APP_StringKeys_View_Home_Index {
            get {
                return ResourceManager.GetString("APP_StringKeys_View_Home_Index", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {first_item}-{last_item} از {all_items}.
        /// </summary>
        public static string APP_StringKeys_View_InfoFormat {
            get {
                return ResourceManager.GetString("APP_StringKeys_View_InfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ردیف.
        /// </summary>
        public static string APP_StringKeys_View_Row {
            get {
                return ResourceManager.GetString("APP_StringKeys_View_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد نتایج در هر صفحه.
        /// </summary>
        public static string APP_StringKeys_View_RowsPerPageString {
            get {
                return ResourceManager.GetString("APP_StringKeys_View_RowsPerPageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت اموال در اختیار پرسنل.
        /// </summary>
        public static string APP_StringKeys_View_Self_expression {
            get {
                return ResourceManager.GetString("APP_StringKeys_View_Self_expression", resourceCulture);
            }
        }
    }
}
